firstName= input ("enter your first name:")
middleName= input ("enter your middle name:")
lastName= input ("enter your last name:")
myAge= input ("enter your age:")
myAddress= input ("enter your address:")
myStatus= input ("enter your status:")
myBirth= input ("enter is your birthday:")
myGoal= input ("enter your goal in life:")
print('thanks!!!!')